/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

const SW_VERSION = '6.35';

// Auto-update: skip waiting and claim clients immediately
self.skipWaiting();
clientsClaim();

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST);

// Runtime caching strategies
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 5 })],
    networkTimeoutSeconds: 3,
  })
);

registerRoute(
  ({ url }) => url.hostname.includes('.cloudfront.net'),
  new CacheFirst({
    cacheName: 'cdn-images',
    plugins: [new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  })
);

registerRoute(
  ({ url }) => url.hostname === 'fonts.googleapis.com',
  new StaleWhileRevalidate({ cacheName: 'google-fonts-stylesheets' })
);

registerRoute(
  ({ url }) => url.hostname === 'fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 })],
  })
);

// ============================================================
// Push Notification Handling
// ============================================================
self.addEventListener('push', function(event) {
  let data: any = { title: '알림', body: '새로운 알림이 있습니다.', icon: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663373200888/9L2UFkGMTFNGvGrFPN8jYv/pwa-icon-192-nZvEU6ium9d2399JoxWmpV.png' };
  try {
    if (event.data) {
      data = Object.assign(data, event.data.json());
    }
  } catch (e) {
    console.error('Push data parse error:', e);
  }

  const options: NotificationOptions = {
    body: data.body,
    icon: data.icon || 'https://d2xsxph8kpxj0f.cloudfront.net/310519663373200888/9L2UFkGMTFNGvGrFPN8jYv/pwa-icon-192-nZvEU6ium9d2399JoxWmpV.png',
    badge: data.badge || 'https://d2xsxph8kpxj0f.cloudfront.net/310519663373200888/9L2UFkGMTFNGvGrFPN8jYv/pwa-icon-192-nZvEU6ium9d2399JoxWmpV.png',
    vibrate: [200, 100, 200],
    data: data.data || { url: '/' },
    actions: data.actions || [],
    tag: data.tag || 'default',
    renotify: true,
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  const notifData = event.notification.data || {};
  let targetUrl = '/';

  // Route by notification type
  if (notifData.type === 'chat_message' && notifData.roomId) {
    targetUrl = '/community/chat/' + notifData.roomId;
  } else if (notifData.type === 'flight_delay' || notifData.type === 'flight_cancel') {
    targetUrl = '/admin/flights';
  } else if (notifData.type === 'schedule_change' || notifData.type === 'schedule_reminder') {
    targetUrl = '/admin/schedule';
  } else if (notifData.type === 'geofence') {
    targetUrl = '/admin/geofence';
  } else if (notifData.type === 'registration_status') {
    targetUrl = '/my-page';
  } else if (notifData.type === 'pickup_time') {
    targetUrl = '/my-page';
  } else if (notifData.url) {
    targetUrl = notifData.url;
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          (client as WindowClient).navigate(targetUrl);
          return (client as WindowClient).focus();
        }
      }
      return self.clients.openWindow(targetUrl);
    })
  );
});

// ============================================================
// Error Reporting
// ============================================================
self.addEventListener('error', function(event) {
  console.error('[SW] Unhandled error:', event.error || event.message);
});

self.addEventListener('unhandledrejection', function(event) {
  console.error('[SW] Unhandled rejection:', event.reason);
});

console.log('[SW] Version', SW_VERSION, 'loaded');
