CREATE TABLE `itineraries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`registrationId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`departureFlightNo` varchar(50),
	`departureAirport` varchar(255),
	`departureTime` timestamp,
	`arrivalFlightNo` varchar(50),
	`arrivalAirport` varchar(255),
	`arrivalTime` timestamp,
	`returnFlightNo` varchar(50),
	`returnDepartureAirport` varchar(255),
	`returnDepartureTime` timestamp,
	`returnArrivalAirport` varchar(255),
	`returnArrivalTime` timestamp,
	`hotelName` varchar(255),
	`hotelAddress` text,
	`hotelCheckIn` timestamp,
	`hotelCheckOut` timestamp,
	`scheduleDetails` json,
	`sentViaWeb` boolean DEFAULT false,
	`sentViaMessenger` boolean DEFAULT false,
	`sentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `itineraries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meetups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`type` enum('meetup','pre_visit','event','meeting','other') NOT NULL DEFAULT 'meetup',
	`locationType` enum('domestic','overseas') NOT NULL DEFAULT 'domestic',
	`destinationCountry` varchar(100),
	`location` varchar(500),
	`scheduleStart` timestamp,
	`scheduleEnd` timestamp,
	`description` text,
	`maxParticipants` int,
	`status` enum('draft','open','closed','completed') NOT NULL DEFAULT 'open',
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meetups_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int,
	`name` varchar(255) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`messengerId` varchar(255) NOT NULL,
	`locationType` enum('domestic','overseas') NOT NULL DEFAULT 'domestic',
	`scheduleStart` timestamp,
	`scheduleEnd` timestamp,
	`walletAddress` varchar(500),
	`referrerName` varchar(255),
	`teamName` varchar(255),
	`teamIntro` text,
	`notes` text,
	`roommatePreference` varchar(255),
	`passportImageUrl` varchar(1000),
	`passportOcrData` json,
	`category` enum('meetup','pre_visit','event','meeting','other') NOT NULL DEFAULT 'meetup',
	`customCategory` varchar(255),
	`status` enum('pending','approved','rejected','completed') NOT NULL DEFAULT 'pending',
	`immigrationAssist` enum('self','agency','pending') NOT NULL DEFAULT 'pending',
	`telegramNotified` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `registrations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `telegram_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`botToken` varchar(500),
	`chatId` varchar(100),
	`enabled` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `telegram_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `travel_info` (
	`id` int AUTO_INCREMENT NOT NULL,
	`countryCode` varchar(10) NOT NULL,
	`countryName` varchar(100) NOT NULL,
	`countryNameKo` varchar(100),
	`requiredItems` json,
	`immigrationUrl` varchar(1000),
	`immigrationNotes` text,
	`visaRequired` boolean DEFAULT false,
	`visaNotes` text,
	`emergencyContact` text,
	`timezone` varchar(100),
	`currency` varchar(50),
	`language` varchar(100),
	`plugType` varchar(100),
	`additionalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `travel_info_id` PRIMARY KEY(`id`),
	CONSTRAINT `travel_info_countryCode_unique` UNIQUE(`countryCode`)
);
