CREATE TABLE `passport_info` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`passportNumber` varchar(50),
	`issuingCountry` varchar(100),
	`nationality` varchar(100),
	`fullName` varchar(255),
	`birthDate` varchar(20),
	`gender` enum('M','F'),
	`issueDate` varchar(20),
	`expiryDate` varchar(20),
	`passportImageUrl` varchar(1000),
	`passportImageKey` varchar(500),
	`ocrData` json,
	`isVerified` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `passport_info_id` PRIMARY KEY(`id`),
	CONSTRAINT `passport_info_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `user_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`phone` varchar(50),
	`nationality` varchar(100),
	`birthDate` varchar(20),
	`gender` enum('male','female','other'),
	`organization` varchar(255),
	`position` varchar(255),
	`department` varchar(255),
	`bio` text,
	`emergencyContact` varchar(255),
	`emergencyPhone` varchar(50),
	`dietaryRestrictions` varchar(500),
	`allergies` text,
	`medicalNotes` text,
	`preferredLanguage` varchar(50) DEFAULT 'ko',
	`telegramId` varchar(255),
	`onboardingCompleted` boolean DEFAULT false,
	`profileImageUrl` varchar(1000),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_profiles_userId_unique` UNIQUE(`userId`)
);
