CREATE TABLE `flight_tickets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int,
	`registrationId` int,
	`passengerName` varchar(255) NOT NULL,
	`passportNumber` varchar(50),
	`nationality` varchar(100),
	`outboundAirline` varchar(255),
	`outboundFlightNo` varchar(50),
	`outboundDepartureAirport` varchar(255),
	`outboundDepartureCode` varchar(10),
	`outboundArrivalAirport` varchar(255),
	`outboundArrivalCode` varchar(10),
	`outboundDepartureDate` varchar(20),
	`outboundDepartureTime` varchar(10),
	`outboundArrivalDate` varchar(20),
	`outboundArrivalTime` varchar(10),
	`outboundSeatClass` varchar(50),
	`outboundSeatNumber` varchar(20),
	`returnAirline` varchar(255),
	`returnFlightNo` varchar(50),
	`returnDepartureAirport` varchar(255),
	`returnDepartureCode` varchar(10),
	`returnArrivalAirport` varchar(255),
	`returnArrivalCode` varchar(10),
	`returnDepartureDate` varchar(20),
	`returnDepartureTime` varchar(10),
	`returnArrivalDate` varchar(20),
	`returnArrivalTime` varchar(10),
	`returnSeatClass` varchar(50),
	`returnSeatNumber` varchar(20),
	`bookingReference` varchar(50),
	`ticketNumber` varchar(50),
	`ticketFileUrl` varchar(1000),
	`ticketFileKey` varchar(500),
	`ticketFileType` enum('image','pdf','generated') DEFAULT 'generated',
	`isGenerated` boolean DEFAULT false,
	`status` enum('active','cancelled','used') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `flight_tickets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `hotel_vouchers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int,
	`registrationId` int,
	`hotelName` varchar(255) NOT NULL,
	`hotelNameLocal` varchar(255),
	`hotelAddress` text NOT NULL,
	`hotelAddressLocal` text,
	`hotelPhone` varchar(100),
	`hotelLatitude` varchar(50),
	`hotelLongitude` varchar(50),
	`bookingId` varchar(100),
	`guestName` varchar(255),
	`roomType` varchar(100),
	`roomCount` int DEFAULT 1,
	`guestsPerRoom` int DEFAULT 1,
	`checkInDate` varchar(20),
	`checkInTime` varchar(10),
	`checkOutDate` varchar(20),
	`checkOutTime` varchar(10),
	`includeMeals` boolean DEFAULT false,
	`specialRequests` text,
	`includes` text,
	`cancellationPolicy` text,
	`checkInInstructions` text,
	`voucherFileUrl` varchar(1000),
	`voucherFileKey` varchar(500),
	`voucherFileType` enum('image','pdf') DEFAULT 'image',
	`localLanguage` varchar(50),
	`localCurrency` varchar(20),
	`status` enum('active','cancelled','expired') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hotel_vouchers_id` PRIMARY KEY(`id`)
);
