CREATE TABLE `affiliate_revenue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingLinkId` int,
	`meetupId` int,
	`platform` enum('trip_com','booking_com','agoda','skyscanner','klook','travelpayouts') NOT NULL,
	`revenueType` enum('flight','hotel','tour','transfer') NOT NULL DEFAULT 'flight',
	`bookingAmount` varchar(50),
	`commissionRate` varchar(20),
	`commissionAmount` varchar(50) NOT NULL,
	`currency` varchar(10) DEFAULT 'USD',
	`status` enum('pending','confirmed','paid','cancelled') NOT NULL DEFAULT 'pending',
	`paidAt` timestamp,
	`externalBookingId` varchar(255),
	`notes` text,
	`revenueMonth` varchar(7),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `affiliate_revenue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `affiliate_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`platform` enum('trip_com','booking_com','agoda','skyscanner','klook','travelpayouts') NOT NULL,
	`affiliateId` varchar(255),
	`apiKey` varchar(500),
	`apiSecret` varchar(500),
	`marker` varchar(255),
	`isActive` boolean DEFAULT false,
	`commissionRateFlight` varchar(20),
	`commissionRateHotel` varchar(20),
	`commissionRateTour` varchar(20),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `affiliate_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `affiliate_settings_platform_unique` UNIQUE(`platform`)
);
--> statement-breakpoint
CREATE TABLE `booking_links` (
	`id` int AUTO_INCREMENT NOT NULL,
	`searchId` int,
	`meetupId` int,
	`userId` int,
	`platform` enum('trip_com','booking_com','agoda','skyscanner','klook','travelpayouts') NOT NULL,
	`linkType` enum('flight','hotel','tour','transfer') NOT NULL DEFAULT 'flight',
	`affiliateUrl` text NOT NULL,
	`originalUrl` text,
	`affiliateId` varchar(255),
	`productName` varchar(500),
	`price` varchar(50),
	`currency` varchar(10) DEFAULT 'USD',
	`clickCount` int DEFAULT 0,
	`lastClickedAt` timestamp,
	`converted` boolean DEFAULT false,
	`conversionAmount` varchar(50),
	`commissionAmount` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `booking_links_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `booking_searches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int,
	`userId` int,
	`searchType` enum('flight','hotel','tour','transfer') NOT NULL DEFAULT 'flight',
	`originCode` varchar(10),
	`originCity` varchar(255),
	`destinationCode` varchar(10),
	`destinationCity` varchar(255),
	`departureDate` varchar(20),
	`returnDate` varchar(20),
	`passengers` int DEFAULT 1,
	`cabinClass` enum('economy','premium_economy','business','first') DEFAULT 'economy',
	`hotelCity` varchar(255),
	`hotelCheckIn` varchar(20),
	`hotelCheckOut` varchar(20),
	`rooms` int DEFAULT 1,
	`guests` int DEFAULT 2,
	`resultCount` int DEFAULT 0,
	`lowestPrice` varchar(50),
	`lowestPricePlatform` varchar(50),
	`searchResults` json,
	`source` enum('backoffice','mypage','telegram') DEFAULT 'backoffice',
	`sentToAttendees` boolean DEFAULT false,
	`sentAt` timestamp,
	`sentCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `booking_searches_id` PRIMARY KEY(`id`)
);
