CREATE TABLE `delivery_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`meetupId` int,
	`providerId` int,
	`providerName` varchar(100),
	`orderType` enum('food','package','document','grocery') DEFAULT 'food',
	`pickupLat` decimal(10,7),
	`pickupLng` decimal(10,7),
	`pickupAddress` text,
	`pickupPlaceName` varchar(500),
	`pickupPhone` varchar(50),
	`deliveryLat` decimal(10,7),
	`deliveryLng` decimal(10,7),
	`deliveryAddress` text,
	`deliveryPlaceName` varchar(500),
	`deliveryPhone` varchar(50),
	`deliveryInstructions` text,
	`restaurantName` varchar(500),
	`restaurantCategory` varchar(100),
	`orderItems` json,
	`packageDescription` text,
	`packageWeight` decimal(8,2),
	`packageSize` enum('small','medium','large','extra_large'),
	`subtotal` decimal(12,2),
	`deliveryFee` decimal(12,2),
	`serviceFee` decimal(12,2),
	`priceLocal` decimal(12,2),
	`localCurrency` varchar(10),
	`priceUsd` decimal(12,2),
	`priceUsdt` decimal(12,2),
	`vatAmount` decimal(12,2) DEFAULT '0',
	`vatRate` decimal(5,2) DEFAULT '0',
	`vatSaved` decimal(12,2) DEFAULT '0',
	`platformMarkup` decimal(12,2) DEFAULT '0',
	`platformRevenue` decimal(12,2) DEFAULT '0',
	`estimatedMinutes` int,
	`distanceKm` decimal(8,2),
	`driverName` varchar(200),
	`driverPhone` varchar(50),
	`orderedAt` timestamp DEFAULT (now()),
	`pickedUpAt` timestamp,
	`deliveredAt` timestamp,
	`paymentMethod` enum('direct_usdt','nowpayments','platform_token','visa_card') DEFAULT 'direct_usdt',
	`paymentTransactionId` int,
	`paymentStatus` enum('pending','paid','refunded','failed') DEFAULT 'pending',
	`status` enum('pending','confirmed','preparing','picked_up','in_transit','delivered','cancelled','refunded') DEFAULT 'pending',
	`cancellationReason` text,
	`externalOrderId` varchar(255),
	`countryCode` varchar(3),
	`rating` int,
	`ratingComment` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `delivery_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `delivery_providers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`apiType` varchar(50) NOT NULL,
	`serviceType` enum('food','package','document','grocery','all') DEFAULT 'all',
	`apiKey` varchar(500),
	`apiSecret` varchar(500),
	`baseUrl` varchar(500),
	`isActive` boolean NOT NULL DEFAULT true,
	`supportedCountries` json,
	`supportedCities` json,
	`commissionRate` decimal(5,2) DEFAULT '12',
	`minOrderAmount` decimal(10,2) DEFAULT '5',
	`logoUrl` varchar(1000),
	`configJson` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `delivery_providers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ride_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`meetupId` int,
	`searchId` int,
	`providerId` int,
	`providerName` varchar(100),
	`pickupLat` decimal(10,7),
	`pickupLng` decimal(10,7),
	`pickupAddress` text,
	`pickupPlaceName` varchar(500),
	`dropoffLat` decimal(10,7),
	`dropoffLng` decimal(10,7),
	`dropoffAddress` text,
	`dropoffPlaceName` varchar(500),
	`vehicleType` enum('economy','comfort','premium','van','suv') DEFAULT 'economy',
	`vehicleName` varchar(200),
	`driverName` varchar(200),
	`driverPhone` varchar(50),
	`licensePlate` varchar(50),
	`passengers` int DEFAULT 1,
	`priceLocal` decimal(12,2),
	`localCurrency` varchar(10),
	`priceUsd` decimal(12,2),
	`priceUsdt` decimal(12,2),
	`vatAmount` decimal(12,2) DEFAULT '0',
	`vatRate` decimal(5,2) DEFAULT '0',
	`vatSaved` decimal(12,2) DEFAULT '0',
	`platformMarkup` decimal(12,2) DEFAULT '0',
	`platformRevenue` decimal(12,2) DEFAULT '0',
	`distanceKm` decimal(8,2),
	`estimatedMinutes` int,
	`scheduledAt` timestamp,
	`pickedUpAt` timestamp,
	`droppedOffAt` timestamp,
	`paymentMethod` enum('direct_usdt','nowpayments','platform_token','visa_card') DEFAULT 'direct_usdt',
	`paymentTransactionId` int,
	`paymentStatus` enum('pending','paid','refunded','failed') DEFAULT 'pending',
	`status` enum('searching','confirmed','driver_assigned','en_route','arrived','in_progress','completed','cancelled') DEFAULT 'searching',
	`cancellationReason` text,
	`externalBookingId` varchar(255),
	`countryCode` varchar(3),
	`rating` int,
	`ratingComment` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ride_bookings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ride_providers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`apiType` varchar(50) NOT NULL,
	`apiKey` varchar(500),
	`apiSecret` varchar(500),
	`baseUrl` varchar(500),
	`isActive` boolean NOT NULL DEFAULT true,
	`supportedCountries` json,
	`supportedCities` json,
	`commissionRate` decimal(5,2) DEFAULT '15',
	`minFare` decimal(10,2) DEFAULT '2',
	`logoUrl` varchar(1000),
	`configJson` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ride_providers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ride_searches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`meetupId` int,
	`pickupLat` decimal(10,7),
	`pickupLng` decimal(10,7),
	`pickupAddress` text,
	`pickupPlaceName` varchar(500),
	`dropoffLat` decimal(10,7),
	`dropoffLng` decimal(10,7),
	`dropoffAddress` text,
	`dropoffPlaceName` varchar(500),
	`countryCode` varchar(3),
	`city` varchar(100),
	`vehicleType` enum('economy','comfort','premium','van','suv') DEFAULT 'economy',
	`passengers` int DEFAULT 1,
	`scheduledAt` timestamp,
	`resultCount` int DEFAULT 0,
	`searchResults` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ride_searches_id` PRIMARY KEY(`id`)
);
