CREATE TABLE `meetup_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int NOT NULL,
	`scheduleType` enum('transport','meal','tour','meeting','free','other') NOT NULL DEFAULT 'other',
	`title` varchar(500) NOT NULL,
	`description` text,
	`location` varchar(500),
	`locationUrl` varchar(1000),
	`eventDate` timestamp NOT NULL,
	`endTime` timestamp,
	`vehicleInfo` varchar(255),
	`driverName` varchar(255),
	`driverPhone` varchar(50),
	`pickupLocation` varchar(500),
	`dropoffLocation` varchar(500),
	`restaurantName` varchar(255),
	`cuisineType` varchar(100),
	`reservationName` varchar(255),
	`reservationPhone` varchar(50),
	`menuInfo` text,
	`costPerPerson` varchar(100),
	`maxParticipants` int,
	`assignedRegistrationIds` json,
	`isAllParticipants` boolean DEFAULT true,
	`notified` boolean DEFAULT false,
	`notifiedAt` timestamp,
	`sortOrder` int DEFAULT 0,
	`status` enum('scheduled','confirmed','in_progress','completed','cancelled') NOT NULL DEFAULT 'scheduled',
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meetup_schedules_id` PRIMARY KEY(`id`)
);
