CREATE TABLE `attendee_tiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int NOT NULL,
	`tierName` varchar(100) NOT NULL,
	`tierLevel` int NOT NULL DEFAULT 0,
	`color` varchar(20) DEFAULT '#6366f1',
	`flightClass` enum('economy','premium_economy','business','first','any') DEFAULT 'economy',
	`maxFlightBudget` decimal(12,2),
	`hotelStars` int DEFAULT 3,
	`maxHotelBudgetPerNight` decimal(12,2),
	`mealAllowance` decimal(12,2),
	`transportAllowance` decimal(12,2),
	`airportPickup` boolean NOT NULL DEFAULT false,
	`loungeAccess` boolean NOT NULL DEFAULT false,
	`prioritySeating` boolean NOT NULL DEFAULT false,
	`giftBag` boolean NOT NULL DEFAULT false,
	`vipDinner` boolean NOT NULL DEFAULT false,
	`dedicatedInterpreter` boolean NOT NULL DEFAULT false,
	`customBenefits` json,
	`description` text,
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `attendee_tiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `emergency_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`registrationId` int,
	`meetupId` int,
	`contactName` varchar(255) NOT NULL,
	`relationship` varchar(100) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`email` varchar(320),
	`countryCode` varchar(5),
	`notes` text,
	`isPrimary` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `emergency_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `safety_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int,
	`alertType` enum('sos','weather','security','health','travel_advisory','general') NOT NULL DEFAULT 'general',
	`severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`title` varchar(500) NOT NULL,
	`description` text,
	`affectedArea` varchar(500),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`radius` int,
	`reportedByUserId` int,
	`reportedByName` varchar(255),
	`status` enum('active','monitoring','resolved','dismissed') NOT NULL DEFAULT 'active',
	`resolvedAt` timestamp,
	`resolvedByUserId` int,
	`resolvedNote` text,
	`notifiedAdmins` boolean NOT NULL DEFAULT false,
	`notifiedParticipants` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `safety_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `travel_policies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int NOT NULL,
	`allowedFlightClass` enum('economy','premium_economy','business','first','any') NOT NULL DEFAULT 'economy',
	`maxFlightBudget` decimal(12,2),
	`flightBudgetCurrency` varchar(10) DEFAULT 'USD',
	`allowedHotelStars` int DEFAULT 3,
	`maxHotelBudgetPerNight` decimal(12,2),
	`hotelBudgetCurrency` varchar(10) DEFAULT 'USD',
	`maxTravelDays` int,
	`minAdvanceBookingDays` int DEFAULT 7,
	`totalBudget` decimal(15,2),
	`totalBudgetCurrency` varchar(10) DEFAULT 'USD',
	`spentAmount` decimal(15,2) DEFAULT '0',
	`requireApproval` boolean NOT NULL DEFAULT false,
	`autoRejectOverBudget` boolean NOT NULL DEFAULT false,
	`policyNotes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `travel_policies_id` PRIMARY KEY(`id`)
);
