CREATE TABLE `rsvp_reminder_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int NOT NULL,
	`invitationId` int NOT NULL,
	`reminderType` enum('d7','d3','d1','custom') NOT NULL,
	`channel` enum('email','sms','telegram','push') NOT NULL DEFAULT 'email',
	`recipientEmail` varchar(320),
	`recipientPhone` varchar(50),
	`recipientName` varchar(255),
	`subject` varchar(500),
	`body` text,
	`status` enum('sent','failed','skipped') NOT NULL DEFAULT 'sent',
	`errorMessage` text,
	`sentAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rsvp_reminder_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rsvp_reminder_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int NOT NULL,
	`enabled` boolean NOT NULL DEFAULT true,
	`reminderDays` json,
	`channels` json,
	`emailSubjectTemplate` varchar(500),
	`emailBodyTemplate` text,
	`smsTemplate` text,
	`lastRunAt` timestamp,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rsvp_reminder_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `self_booking_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`meetupId` int NOT NULL,
	`registrationId` int NOT NULL,
	`userId` int NOT NULL,
	`bookingType` enum('flight','hotel','both') NOT NULL,
	`flightDepartureCity` varchar(100),
	`flightArrivalCity` varchar(100),
	`flightDepartureDate` varchar(20),
	`flightReturnDate` varchar(20),
	`flightClass` enum('economy','premium_economy','business','first') DEFAULT 'economy',
	`flightPreferences` text,
	`hotelCity` varchar(100),
	`hotelCheckIn` varchar(20),
	`hotelCheckOut` varchar(20),
	`hotelStarRating` int,
	`hotelRoomType` varchar(100),
	`hotelPreferences` text,
	`estimatedBudget` decimal(12,2),
	`currency` varchar(10) DEFAULT 'USD',
	`policyCompliant` boolean DEFAULT true,
	`policyViolations` json,
	`status` enum('draft','submitted','approved','rejected','booked','cancelled') NOT NULL DEFAULT 'draft',
	`approvedBy` int,
	`approvedAt` timestamp,
	`rejectionReason` text,
	`linkedBookingId` int,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `self_booking_requests_id` PRIMARY KEY(`id`)
);
